services:
  http:
    build: .
    container_name: dating-site-http
    # ports:
    #  - "8080:8080"
    env_file: .env
    volumes:
      - ./dating/media/:/app/dating/media/
    restart: always
    depends_on:
      - db

  websockets:
    build: .
    command: ["daphne","-b","0.0.0.0","-p","8081","dating.asgi:application"]
    # command: ["python3","manage.py","runserver","--setting=dating.settings.prod"]
    container_name: dating-site-websocket
    # ports:
    #  - "8080:8080"
    #  - "8081:8000"
    env_file: .env 
    restart: always
    depends_on: 
      - redis
    
  celery:
    build: .
    command: ["celery", "-A", "dating.celery", "worker", "-l", "INFO", "-P", "gevent"]
    container_name: celery
    env_file: .env
    restart: always
    depends_on:
      - http
      - rabbitmq

  db:
    image: postgres:17.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dating_postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - D:\Docker\Redis\redisdata:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
    command: >
      sh -c '
          mkdir -p /usr/local/etc/redis &&
          echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
          echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
          echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
          echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
          echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
          echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
          redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - D:\Docker\RabbitMQ\rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  nginx:
    image: nginx:alpine-custom
    container_name: nginx
    restart: always
    ports: 
      - "8090:8080"
    volumes:
      - ./staticfiles:/staticfiles
      - ./dating/media:/media
    depends_on:
      - http
      - websockets
volumes:
  dating_postgres_data:

