# Generated by Django 5.1.3 on 2024-11-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_datinguser_date_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interst',
            new_name='Interest',
        ),
    ]
