# Generated by Django 5.1.3 on 2024-11-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_datinguser_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='datinguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/accounts/'),
        ),
    ]
