# Generated by Django 5.1.3 on 2024-11-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_datinguser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datinguser',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
