# Generated by Django 5.1.3 on 2024-11-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_datinguser_date_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datinguser',
            old_name='Interests',
            new_name='interests',
        ),
    ]
