# Generated by Django 5.1.3 on 2024-11-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_interests_datinguser_interests'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='datinguser',
            name='gender',
            field=models.CharField(choices=[('UNK', 'unknown'), ('ML', 'male'), ('FL', 'female')], default='UNK', max_length=3),
        ),
        migrations.AddIndex(
            model_name='datinguser',
            index=models.Index(fields=['gender'], name='accounts_da_gender_0421b9_idx'),
        ),
    ]
