# Generated by Django 5.1.3 on 2024-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_datinguser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datinguser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
