# Generated by Django 5.1.3 on 2024-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_datinguser_age'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datinguser',
            index=models.Index(fields=['age'], name='accounts_da_age_22cf45_idx'),
        ),
    ]
